UPDATE api.assets SET name = 'S&P 500 ETF (iShares)', description = 'Die 500 größten US-Unternehmen – Apple, Microsoft, Amazon & Co.' WHERE id = 1170;
UPDATE api.assets SET name = 'S&P 500 ETF (iShares, Mailand)', description = 'Wie SXR8.DE, an der Mailänder Börse gelistet' WHERE id = 1171;
UPDATE api.assets SET name = 'MSCI World ETF (iShares)', description = '1.400 Unternehmen aus 23 Industrieländern weltweit' WHERE id = 1172;
UPDATE api.assets SET name = 'MSCI World ETF (iShares, Amsterdam)', description = 'Wie EUNL.DE, an der Amsterdamer Börse gelistet' WHERE id = 1173;
UPDATE api.assets SET name = 'MSCI Europe ETF (iShares)', description = 'Die größten Unternehmen aus Europa – Nestlé, LVMH, SAP & Co.' WHERE id = 1174;
UPDATE api.assets SET name = 'MSCI Europe ETF (iShares, Amsterdam)', description = 'Wie EUNK.DE, an der Amsterdamer Börse gelistet' WHERE id = 1175;
UPDATE api.assets SET name = 'MSCI Europe ETF (iShares, Mailand)', description = 'Wie EUNK.DE, an der Mailänder Börse gelistet' WHERE id = 1176;
UPDATE api.assets SET name = 'Schwellenländer ETF (iShares)', description = 'Unternehmen aus Wachstumsmärkten wie China, Indien, Brasilien' WHERE id = 1177;
UPDATE api.assets SET name = 'Schwellenländer ETF (iShares, Frankfurt)', description = 'Wie EMIM.AS, an der Frankfurter Börse gelistet' WHERE id = 1178;
UPDATE api.assets SET name = 'S&P 500 ETF (iShares, USA)', description = 'Die 500 größten US-Unternehmen, US-gelistete Version' WHERE id = 1179;
UPDATE api.assets SET name = 'S&P 500 ETF (iShares, London)', description = 'Die 500 größten US-Unternehmen, an der Londoner Börse gelistet' WHERE id = 1180;
UPDATE api.assets SET name = 'MSCI World ETF (iShares, London)', description = '1.400 Unternehmen weltweit, an der Londoner Börse gelistet' WHERE id = 1181;
UPDATE api.assets SET name = 'MSCI World ETF (iShares, Mailand)', description = '1.400 Unternehmen weltweit, an der Mailänder Börse gelistet' WHERE id = 1182;
UPDATE api.assets SET name = 'MSCI World ETF ausschüttend (iShares)', description = 'Wie SWDA.L, zahlt Gewinne regelmäßig aus statt reinvestieren' WHERE id = 1183;
UPDATE api.assets SET name = 'US-Gesamtmarkt ETF (iShares)', description = 'Fast alle börsennotierten US-Unternehmen in einem ETF' WHERE id = 1184;
UPDATE api.assets SET name = 'US-Anleihen ETF (iShares)', description = 'Viele verschiedene US-Anleihen gebündelt – stabiler als Aktien' WHERE id = 1185;
UPDATE api.assets SET name = 'Dividenden ETF (iShares)', description = 'US-Unternehmen die regelmäßig hohe Dividenden ausschütten' WHERE id = 1186;
UPDATE api.assets SET name = 'Dividendenwachstum ETF (iShares)', description = 'US-Unternehmen die ihre Dividende jedes Jahr steigern' WHERE id = 1187;
UPDATE api.assets SET name = 'Europa ETF (Vanguard)', description = 'Die größten Unternehmen aus Europa' WHERE id = 1188;
UPDATE api.assets SET name = 'Industrieländer ETF (Vanguard)', description = 'Entwickelte Märkte weltweit außer USA – Europa, Japan, Australien' WHERE id = 1189;
UPDATE api.assets SET name = 'Welt ohne USA ETF (Vanguard)', description = 'Alle Industrieländer und Schwellenländer – nur ohne US-Unternehmen' WHERE id = 1190;
UPDATE api.assets SET name = 'US-Gesamtmarkt ETF (Vanguard)', description = 'Fast alle börsennotierten US-Unternehmen – über 3.500 Firmen' WHERE id = 1191;
UPDATE api.assets SET name = 'FTSE All-World ETF (Vanguard)', description = 'Über 3.700 Unternehmen aus aller Welt – Industrie- und Schwellenländer' WHERE id = 1192;
UPDATE api.assets SET name = 'FTSE All-World ETF (Vanguard, London)', description = 'Wie VWCE.DE, an der Londoner Börse gelistet' WHERE id = 1193;
UPDATE api.assets SET name = 'Industrieländer ETF (Vanguard, Mailand)', description = 'Entwickelte Märkte weltweit, an der Mailänder Börse gelistet' WHERE id = 1194;
UPDATE api.assets SET name = 'FTSE 100 ETF (Vanguard)', description = 'Die 100 größten britischen Unternehmen – BP, HSBC, Unilever & Co.' WHERE id = 1195;
UPDATE api.assets SET name = 'MSCI World ETF (Amundi)', description = '1.400 Unternehmen weltweit, besonders günstig (TER 0,12 %)' WHERE id = 1196;
UPDATE api.assets SET name = 'S&P 500 ETF (Amundi, Paris)', description = 'Die 500 größten US-Unternehmen, günstige Amundi-Version' WHERE id = 1198;
UPDATE api.assets SET name = 'S&P 500 ETF (Amundi, Mailand)', description = 'Wie 500.PA, an der Mailänder Börse gelistet' WHERE id = 1199;
UPDATE api.assets SET name = 'Nasdaq-100 ETF (Amundi)', description = 'Die 100 größten Tech-Unternehmen – Apple, NVIDIA, Google & Co.' WHERE id = 1200;
UPDATE api.assets SET name = 'Nasdaq-100 ETF (Amundi, Mailand)', description = 'Wie ANX.PA, an der Mailänder Börse gelistet' WHERE id = 1201;
UPDATE api.assets SET name = 'Stoxx Europe 600 ETF (Amundi)', description = 'Die 600 größten europäischen Unternehmen' WHERE id = 1202;
UPDATE api.assets SET name = 'Stoxx Europe 600 ETF (Amundi, Paris)', description = 'Wie LYP6.DE, an der Pariser Börse gelistet' WHERE id = 1203;
UPDATE api.assets SET name = 'All Country World ETF (Amundi)', description = 'Über 2.000 Unternehmen aus Industrie- und Schwellenländern weltweit' WHERE id = 1204;
UPDATE api.assets SET name = 'Schwellenländer ETF (Amundi, Mailand)', description = 'Unternehmen aus Wachstumsmärkten wie China, Indien, Brasilien' WHERE id = 1205;
