CREATE EXTENSION IF NOT EXISTS timescaledb;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- =============================================================================
-- AUTH
-- =============================================================================

CREATE ROLE auth_admin NOINHERIT LOGIN PASSWORD :'AUTH_ADMIN_PASSWORD';
CREATE SCHEMA IF NOT EXISTS auth AUTHORIZATION auth_admin;
GRANT CREATE ON DATABASE postgres TO auth_admin;
ALTER USER auth_admin SET search_path = auth;

-- =============================================================================
-- SCHEMA & TYPES
-- =============================================================================

CREATE SCHEMA api;
CREATE SCHEMA depots;

CREATE TYPE AssetType AS ENUM ('commodity', 'crypto', 'fund', 'stock');
CREATE TYPE TransactionType AS ENUM ('user', 'savings_plan');
CREATE TYPE SavingsPeriod AS ENUM ('annually', 'monthly', 'weekly', 'daily');

-- =============================================================================
-- API TABLES
-- =============================================================================

CREATE TABLE IF NOT EXISTS api.assets (
  id          bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  symbol      text NOT NULL,
  name        text NOT NULL,
  description text,
  asset_type  AssetType NOT NULL,
  last_updated date,
  CONSTRAINT AssetInfo_pkey          PRIMARY KEY (id),
  CONSTRAINT AssetInfo_unique_symbol UNIQUE (symbol)
);

CREATE INDEX idx_asset_symbol        ON api.assets USING HASH (symbol);
CREATE INDEX assets_symbol_trgm_idx  ON api.assets USING GIN (symbol gin_trgm_ops);
CREATE INDEX assets_name_trgm_idx    ON api.assets USING GIN (name gin_trgm_ops);
CREATE INDEX assets_description_trgm_idx ON api.assets USING GIN (description gin_trgm_ops);

CREATE TABLE api.asset_prices (
  asset_id bigint NOT NULL,
  tstamp   date   NOT NULL,
  open     REAL,
  close    REAL,
  high     real,
  low      real,
  volume   bigint,
  CONSTRAINT AssetPrices_pkey         PRIMARY KEY (asset_id, tstamp),
  CONSTRAINT AssetPrices_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES api.assets (id)
);

SELECT create_hypertable(
  'api.asset_prices',
  'tstamp',
  if_not_exists  => true,
  migrate_data   => true
);

-- Covering index for latest-price lookups (used heavily in get_position_profits)
CREATE INDEX IF NOT EXISTS idx_asset_prices_asset_tstamp
  ON api.asset_prices (asset_id, tstamp DESC);

-- TimescaleDB continuous aggregate: weekly OHLCV
CREATE MATERIALIZED VIEW api.asset_prices_weekly
WITH (timescaledb.continuous) AS
SELECT
  d.asset_id,
  time_bucket(INTERVAL '1 week', d.tstamp) AS tstamp,
  FIRST(d.open,  d.tstamp) AS open,
  MAX(d.high)              AS high,
  MIN(d.low)               AS low,
  LAST(d.close,  d.tstamp) AS close,
  SUM(d.volume)            AS volume
FROM api.asset_prices d
GROUP BY d.asset_id, time_bucket(INTERVAL '1 week', d.tstamp);

SELECT add_continuous_aggregate_policy(
  'api.asset_prices_weekly',
  start_offset      => INTERVAL '3 weeks',
  end_offset        => INTERVAL '1 day',
  schedule_interval => INTERVAL '1 day'
);

-- =============================================================================
-- DEPOT TABLES
-- =============================================================================

CREATE TABLE IF NOT EXISTS depots.depots (
  created    timestamp NOT NULL,
  cash       bigint    NOT NULL,
  cash_start bigint    NOT NULL,
  users      uuid[]    NOT NULL,
  id         bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  CONSTRAINT Depots_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS depots.positions (
  id       bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  asset_id bigint NOT NULL,
  amount   real   NOT NULL,
  price    real   NOT NULL,
  worth    real   NOT NULL,
  last     DATE,
  depot_id bigint NOT NULL,
  CONSTRAINT Positions_pkey         PRIMARY KEY (id),
  CONSTRAINT unique_depot_asset     UNIQUE (depot_id, asset_id),
  CONSTRAINT Positions_asset_pkey   FOREIGN KEY (asset_id) REFERENCES api.assets (id),
  CONSTRAINT Positions_depot_pkey   FOREIGN KEY (depot_id) REFERENCES depots.depots (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_position_asset_depot ON depots.positions (asset_id, depot_id);
CREATE INDEX IF NOT EXISTS idx_position_asset        ON depots.positions (asset_id);
CREATE INDEX IF NOT EXISTS idx_position_depot        ON depots.positions (depot_id);

CREATE TABLE IF NOT EXISTS depots.transactions (
  depot_id   bigint    NOT NULL,
  user_id    uuid,
  asset_id   bigint    NOT NULL,
  amount     real      NOT NULL,
  price      real      NOT NULL,
  tstamp     timestamp NOT NULL DEFAULT NOW(),
  commission real      NOT NULL,
  type       TransactionType NOT NULL DEFAULT 'user',
  id         bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  CONSTRAINT Transactions_pkey       PRIMARY KEY (id),
  CONSTRAINT Transactions_depot_fkey FOREIGN KEY (depot_id) REFERENCES depots.depots (id) ON DELETE CASCADE,
  CONSTRAINT Transactions_stock_fkey FOREIGN KEY (asset_id) REFERENCES api.assets (id)
);

CREATE INDEX IF NOT EXISTS idx_transaction_assets_depot       ON depots.transactions (asset_id, depot_id);
CREATE INDEX IF NOT EXISTS idx_transaction_asset               ON depots.transactions (asset_id);
CREATE INDEX IF NOT EXISTS idx_transaction_depot               ON depots.transactions (depot_id);
-- Covering index for aggregated_transactions_mat GROUP BY
CREATE INDEX IF NOT EXISTS idx_transactions_depot_asset_date
  ON depots.transactions (depot_id, asset_id, (tstamp::date));

CREATE TABLE IF NOT EXISTS depots.savings_plans (
  id           bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  depot_id     bigint         NOT NULL,
  asset_id     bigint         NOT NULL,
  worth        real           NOT NULL,
  period       SavingsPeriod  NOT NULL,
  created      timestamp      NOT NULL,
  last_changed timestamp      NOT NULL,
  last_executed date          DEFAULT NULL,
  created_by   uuid           NOT NULL,
  CONSTRAINT Savings_pkey       PRIMARY KEY (asset_id, depot_id),
  CONSTRAINT Savings_depot_fkey FOREIGN KEY (depot_id) REFERENCES depots.depots (id) ON DELETE CASCADE,
  CONSTRAINT Savings_stock_fkey FOREIGN KEY (asset_id) REFERENCES api.assets (id)
);

CREATE INDEX IF NOT EXISTS idx_savings_assets_depot ON depots.savings_plans (asset_id, depot_id);
CREATE INDEX IF NOT EXISTS idx_savings_asset         ON depots.savings_plans (asset_id);
CREATE INDEX IF NOT EXISTS idx_savings_depot         ON depots.savings_plans (depot_id);

-- =============================================================================
-- HELPER FUNCTIONS
-- =============================================================================

CREATE OR REPLACE FUNCTION depots.transaction_affects_cash(t TransactionType)
RETURNS boolean LANGUAGE sql IMMUTABLE AS $$
  SELECT t = 'user';
$$;

CREATE OR REPLACE FUNCTION depots.transaction_affects_commission(t TransactionType)
RETURNS boolean LANGUAGE sql IMMUTABLE AS $$
  SELECT TRUE;
$$;

CREATE OR REPLACE FUNCTION depots.sp_to_per_month(period SavingsPeriod)
RETURNS NUMERIC LANGUAGE plpgsql IMMUTABLE AS $$
BEGIN
  RETURN CASE period
    WHEN 'daily'    THEN 365.0 / 12
    WHEN 'weekly'   THEN 52.0  / 12
    WHEN 'monthly'  THEN 1
    WHEN 'annually' THEN 1.0   / 12
  END;
END;
$$;

CREATE OR REPLACE FUNCTION depots.sp_to_interval(period SavingsPeriod)
RETURNS INTERVAL LANGUAGE plpgsql IMMUTABLE AS $$
BEGIN
  RETURN CASE period
    WHEN 'daily'    THEN '1 day'
    WHEN 'weekly'   THEN '1 week'
    WHEN 'monthly'  THEN '1 month'
    WHEN 'annually' THEN '1 year'
  END;
END;
$$;

-- =============================================================================
-- MATERIALIZED VIEWS  (replacing the old views for performance)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- aggregated_transactions_mat
-- Running totals per depot/asset/day. Window functions run once on refresh,
-- not on every query.
-- -----------------------------------------------------------------------------

CREATE MATERIALIZED VIEW depots.aggregated_transactions_mat AS
WITH daily_totals AS (
  SELECT
    depot_id,
    asset_id,
    date(tstamp) AS tstamp,
    SUM(
      CASE WHEN depots.transaction_affects_cash(type)
        THEN amount * price ELSE 0 END
    ) AS daily_expenses,
    SUM(amount) AS daily_amount,
    SUM(
      CASE WHEN depots.transaction_affects_commission(type)
        THEN commission ELSE 0 END
    ) AS daily_commission
  FROM depots.transactions
  GROUP BY depot_id, asset_id, date(tstamp)
)
SELECT
  depot_id,
  asset_id,
  tstamp,
  daily_amount,
  daily_commission,
  SUM(daily_expenses)   OVER w AS running_expenses,
  SUM(daily_amount)     OVER w AS running_amount,
  SUM(daily_commission) OVER w AS running_commission
FROM daily_totals
WINDOW w AS (
  PARTITION BY depot_id, asset_id
  ORDER BY tstamp
  ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
)
ORDER BY depot_id, asset_id, tstamp
WITH DATA;

-- Required for CONCURRENTLY refresh
CREATE UNIQUE INDEX idx_agg_tx_mat_unique
  ON depots.aggregated_transactions_mat (depot_id, asset_id, tstamp);

-- -----------------------------------------------------------------------------
-- position_values_mat
-- Daily market value + profit per depot/asset. Reads from the matview above
-- so no window functions run at query time.
-- -----------------------------------------------------------------------------

CREATE MATERIALIZED VIEW depots.position_values_mat AS
WITH depot_first_transaction AS (
  SELECT depot_id, MIN(tstamp::date) AS first_date
  FROM depots.transactions
  GROUP BY depot_id
),
depot_assets AS (
  SELECT DISTINCT depot_id, asset_id
  FROM depots.transactions
),
date_range AS (
  SELECT
    da.depot_id,
    da.asset_id,
    generate_series(dft.first_date, CURRENT_DATE, '1 day'::interval)::date AS tstamp
  FROM depot_assets da
  JOIN depot_first_transaction dft ON da.depot_id = dft.depot_id
)
SELECT
  dr.depot_id,
  dr.tstamp,
  dr.asset_id,
  t.running_amount,
  t.running_commission,
  t.running_expenses,
  ap.close                                                              AS price,
  t.running_amount * ap.close                                           AS market_value,
  (t.running_amount * ap.close) - t.running_expenses - t.running_commission AS position_profit
FROM date_range dr
INNER JOIN LATERAL (
  SELECT running_amount, running_commission, running_expenses
  FROM depots.aggregated_transactions_mat t
  WHERE t.depot_id = dr.depot_id
    AND t.asset_id = dr.asset_id
    AND t.tstamp  <= dr.tstamp
  ORDER BY t.tstamp DESC
  LIMIT 1
) t ON TRUE
LEFT JOIN LATERAL (
  SELECT close
  FROM api.asset_prices
  WHERE asset_id = dr.asset_id
    AND tstamp   <= dr.tstamp
  ORDER BY tstamp DESC
  LIMIT 1
) ap ON TRUE
WHERE ap.close IS NOT NULL
ORDER BY dr.depot_id, dr.tstamp, dr.asset_id
WITH DATA;

-- Required for CONCURRENTLY refresh
CREATE UNIQUE INDEX idx_position_values_mat_unique
  ON depots.position_values_mat (depot_id, asset_id, tstamp);

-- Optimised for GROUP BY in depots.values
CREATE INDEX idx_position_values_mat_depot_tstamp
  ON depots.position_values_mat (depot_id, tstamp);

-- Optimised for LATERAL join in get_position_profits
CREATE INDEX idx_position_values_mat_asset_depot
  ON depots.position_values_mat (asset_id, depot_id);

-- =============================================================================
-- VIEWS  (cheap — sit on top of the matviews above)
-- =============================================================================

-- depots.values — simple GROUP BY on the matview, fast
CREATE OR REPLACE VIEW depots.values AS
SELECT
  pv.depot_id,
  pv.tstamp,
  d.cash_start + SUM(pv.position_profit)                            AS value,
  d.cash_start - SUM(pv.running_commission + pv.running_expenses)   AS cash,
  SUM(pv.position_profit)                                           AS profit_from_start,
  SUM(pv.market_value)                                              AS assets
FROM depots.position_values_mat pv
JOIN depots.depots d ON pv.depot_id = d.id
GROUP BY pv.depot_id, pv.tstamp, d.cash_start
ORDER BY pv.depot_id, pv.tstamp;

-- depots.aggregated_values — one row per depot with diff columns
-- FIX: prev_1y_total now has correct PARTITION BY depot_id
-- FIX: missing comma after profit_from_start corrected
CREATE OR REPLACE VIEW depots.aggregated_values AS
WITH latest_per_depot AS (
  SELECT
    assets,
    depot_id,
    cash,
    profit_from_start,
    value AS total,
    tstamp,
    NTH_VALUE(value, 2) OVER (
      PARTITION BY depot_id ORDER BY tstamp DESC
      ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
    ) AS prev_1d_total,
    NTH_VALUE(value, 23) OVER (
      PARTITION BY depot_id ORDER BY tstamp DESC
      ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
    ) AS prev_1m_total,
    -- FIX: was missing PARTITION BY depot_id — was mixing rows across depots
    NTH_VALUE(value, 253) OVER (
      PARTITION BY depot_id ORDER BY tstamp DESC
      ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
    ) AS prev_1y_total,
    ROW_NUMBER() OVER (PARTITION BY depot_id ORDER BY tstamp DESC) AS rn
  FROM depots.values
)
SELECT
  assets,
  depot_id,
  cash,
  total,
  profit_from_start,
  tstamp,
  prev_1d_total,
  prev_1m_total,
  prev_1y_total,
  total - prev_1d_total                              AS diff_1d,
  total - prev_1m_total                              AS diff_1m,
  total - prev_1y_total                              AS diff_1y,
  (total - prev_1d_total) / NULLIF(prev_1d_total, 0) * 100 AS rel_diff_1d,
  (total - prev_1m_total) / NULLIF(prev_1m_total, 0) * 100 AS rel_diff_1m,
  (total - prev_1y_total) / NULLIF(prev_1y_total, 0) * 100 AS rel_diff_1y
FROM latest_per_depot
WHERE rn = 1;

-- =============================================================================
-- FUNCTIONS
-- =============================================================================

-- get_position_profits — scoped to one depot, only fetches prices for
-- assets the depot actually holds (avoids full table scan)
CREATE OR REPLACE FUNCTION depots.get_position_profits(p_depot_id INT)
RETURNS TABLE (
  depot_id       INT,
  asset_id       INT,
  symbol         TEXT,
  name           TEXT,
  asset_type     TEXT,
  description    TEXT,
  current_amount NUMERIC,
  total_invested NUMERIC,
  total_sold     NUMERIC,
  current_price  NUMERIC,
  market_value   NUMERIC,
  total_profit   NUMERIC
)
LANGUAGE sql STABLE AS $$
  WITH position_summary AS (
    SELECT
      t.depot_id,
      t.asset_id,
      SUM(t.amount)                                                          AS current_amount,
      SUM(CASE WHEN t.amount > 0 THEN t.amount * t.price + t.commission ELSE 0 END) AS total_invested,
      SUM(CASE WHEN t.amount < 0 THEN ABS(t.amount * t.price) - t.commission ELSE 0 END) AS total_sold
    FROM depots.transactions t
    WHERE t.depot_id = p_depot_id
    GROUP BY t.depot_id, t.asset_id
    HAVING SUM(t.amount) > 0
  ),
  latest_prices AS (
    SELECT DISTINCT ON (asset_id)
      asset_id,
      close AS current_price
    FROM api.asset_prices
    WHERE close    IS NOT NULL
      AND asset_id IN (SELECT asset_id FROM position_summary)
    ORDER BY asset_id, tstamp DESC
  )
  SELECT
    ps.depot_id,
    ps.asset_id,
    a.symbol,
    a.name,
    a.asset_type::text,
    a.description,
    ps.current_amount,
    ps.total_invested,
    ps.total_sold,
    lp.current_price,
    ps.current_amount * lp.current_price                                        AS market_value,
    ps.total_sold + (ps.current_amount * lp.current_price) - ps.total_invested  AS total_profit
  FROM position_summary ps
  JOIN api.assets a ON ps.asset_id = a.id
  LEFT JOIN latest_prices lp ON ps.asset_id = lp.asset_id;
$$;

-- get_transactions_with_position — calls get_position_profits once,
-- joins result against filtered transactions (no repeated view evaluation)
CREATE OR REPLACE FUNCTION depots.get_transactions_with_position(p_depot_id INT)
RETURNS TABLE (
  depot_id       INT,
  user_id        UUID,
  asset_id       INT,
  amount         NUMERIC,
  price          NUMERIC,
  tstamp         TIMESTAMPTZ,
  commission     NUMERIC,
  id             INT,
  symbol         TEXT,
  description    TEXT,
  asset_type     TEXT,
  current_amount NUMERIC,
  total_invested NUMERIC,
  total_sold     NUMERIC,
  total_profit   NUMERIC,
  current_price  NUMERIC,
  market_value   NUMERIC,
  type           TEXT
)
LANGUAGE sql STABLE AS $$
  SELECT
    dt.depot_id,
    dt.user_id,
    dt.asset_id,
    dt.amount,
    dt.price,
    dt.tstamp,
    dt.commission,
    dt.id,
    pp.symbol,
    pp.description,
    pp.asset_type,
    pp.current_amount,
    pp.total_invested,
    pp.total_sold,
    pp.total_profit,
    pp.current_price,
    pp.market_value,
    dt.type::text
  FROM depots.transactions dt
  LEFT JOIN depots.get_position_profits(p_depot_id) pp
    ON pp.asset_id = dt.asset_id
  WHERE dt.depot_id = p_depot_id;
$$;

-- search_assets — fuzzy search with trigram scoring
CREATE OR REPLACE FUNCTION api.search_assets(
  search_query      text,
  asset_type_filter text    DEFAULT NULL,
  result_limit      integer DEFAULT 20
)
RETURNS TABLE (
  id             bigint,
  symbol         text,
  name           text,
  description    text,
  asset_type     text,
  last_updated   date,
  relevance_score numeric
)
LANGUAGE plpgsql STABLE AS $$
BEGIN
  RETURN QUERY
  SELECT
    a.id,
    a.symbol,
    a.name,
    a.description,
    a.asset_type::text,
    a.last_updated,
    ROUND(CAST(
      CASE WHEN LOWER(a.symbol) = LOWER(search_query) THEN 100
           WHEN LOWER(a.name)   = LOWER(search_query) THEN 95
           ELSE 0 END
      + CASE WHEN LOWER(a.symbol) LIKE LOWER(search_query) || '%' THEN 50
             WHEN LOWER(a.name)   LIKE LOWER(search_query) || '%' THEN 45
             ELSE 0 END
      + similarity(a.symbol, search_query) * 40
      + similarity(a.name,   search_query) * 35
      + COALESCE(similarity(a.description, search_query) * 15, 0)
      + CASE WHEN LOWER(a.symbol) LIKE '%' || LOWER(search_query) || '%' THEN 10
             WHEN LOWER(a.name)   LIKE '%' || LOWER(search_query) || '%' THEN 8
             ELSE 0 END
    AS numeric), 2) AS relevance_score
  FROM api.assets a
  WHERE (
    a.symbol      % search_query OR
    a.name        % search_query OR
    a.description % search_query OR
    LOWER(a.symbol)      LIKE '%' || LOWER(search_query) || '%' OR
    LOWER(a.name)        LIKE '%' || LOWER(search_query) || '%' OR
    LOWER(a.description) LIKE '%' || LOWER(search_query) || '%'
  )
  AND (asset_type_filter IS NULL OR a.asset_type::text = asset_type_filter)
  ORDER BY relevance_score DESC, a.name ASC
  LIMIT result_limit;
END;
$$;

-- =============================================================================
-- MATVIEW REFRESH JOB  (TimescaleDB background worker, runs daily at 02:00)
-- Order matters: aggregated_transactions_mat before position_values_mat
-- =============================================================================

CREATE OR REPLACE PROCEDURE depots.refresh_depot_mats(job_id int, config jsonb)
LANGUAGE plpgsql AS $$
BEGIN
  REFRESH MATERIALIZED VIEW CONCURRENTLY depots.aggregated_transactions_mat;
  REFRESH MATERIALIZED VIEW CONCURRENTLY depots.position_values_mat;
END;
$$;

SELECT add_job(
  proc              => 'depots.refresh_depot_mats',
  schedule_interval => INTERVAL '1 day',
  initial_start     => date_trunc('day', NOW()) + INTERVAL '2 hours',
  scheduled         => true,
  fixed_schedule    => true
);

-- =============================================================================
-- ROLES & PERMISSIONS
-- =============================================================================

CREATE ROLE anon          NOINHERIT NOLOGIN;
CREATE ROLE authenticated NOINHERIT NOLOGIN;
CREATE ROLE authenticator NOINHERIT LOGIN PASSWORD :'AUTHENTICATOR_PASSWORD';
CREATE ROLE service_worker NOINHERIT BYPASSRLS LOGIN PASSWORD :'SERVICE_WORKER_PASSWORD';

ALTER ROLE anon SET search_path = api;

-- authenticator inherits both anon and authenticated
GRANT anon         TO authenticator;
GRANT authenticated TO authenticator;
GRANT CONNECT ON DATABASE postgres TO authenticator;

-- service_worker
GRANT CONNECT ON DATABASE postgres TO service_worker;

GRANT USAGE ON SCHEMA api    TO service_worker;
GRANT USAGE ON SCHEMA depots TO service_worker;

GRANT SELECT, INSERT, UPDATE, DELETE ON api.assets       TO service_worker;
GRANT SELECT, INSERT, UPDATE, DELETE ON api.asset_prices TO service_worker;
GRANT USAGE ON SEQUENCE api.assets_id_seq                TO service_worker;

GRANT SELECT, INSERT, UPDATE, DELETE ON depots.depots       TO service_worker;
GRANT SELECT, INSERT, UPDATE, DELETE ON depots.positions     TO service_worker;
GRANT SELECT, INSERT, UPDATE, DELETE ON depots.transactions  TO service_worker;
GRANT SELECT, INSERT, UPDATE, DELETE ON depots.savings_plans TO service_worker;
GRANT USAGE ON SEQUENCE depots.depots_id_seq        TO service_worker;
GRANT USAGE ON SEQUENCE depots.positions_id_seq     TO service_worker;
GRANT USAGE ON SEQUENCE depots.transactions_id_seq  TO service_worker;
GRANT USAGE ON SEQUENCE depots.savings_plans_id_seq TO service_worker;

-- authenticator / authenticated
GRANT USAGE ON SCHEMA depots TO authenticator;
GRANT SELECT ON depots.depots TO authenticator;

-- RLS
ALTER TABLE api.assets       ENABLE ROW LEVEL SECURITY;
ALTER TABLE api.asset_prices ENABLE ROW LEVEL SECURITY;

-- search_assets accessible to all
GRANT EXECUTE ON FUNCTION api.search_assets(text, text, integer) TO anon, authenticated;

-- =============================================================================
-- DATABASE CONFIG
-- =============================================================================

ALTER DATABASE postgres SET config.commission             = '1';
ALTER DATABASE postgres SET config.monthly_budget_start   = '200';

GRANT SELECT ON depots.values TO authenticated;
GRANT SELECT ON depots.values TO anon;GRANT SELECT ON ALL TABLES IN SCHEMA depots TO authenticated;
